name: covid-ui
channels:
  - conda-forge
  - defaults
  - bioconda
dependencies:
  - python=3.8.3
  - numpy=1.18.5
  - networkx=2.4
  - pandas=1.0.5
  - tqdm=4.46.1
  - xlrd=1.2.0
  - bowtie2=2.4.1
  - biopython=1.76
  - pip=20.1.1
  - pip:
      - pysam==0.16.0.1
  # If you want to run the notebooks:
  - jupyter=1.0.0
  - jupyter_contrib_nbextensions=0.5.1
